### ISSUE TITLE
diffview opens empty

### ISSUE THREAD

**Issue by cloggier** [TimUntersberger/neogit#136] opened 2021-06-03 19:59 UTC
Diffview, neogit and plenary installed used packer:

```lua
use {
  "TimUntersberger/neogit",
  config = require "plugin._neogit",
  requires = {
    "nvim-lua/plenary.nvim",
    {
      "sindrets/diffview.nvim",
      config = function()
        require "diffview".setup {file_panel = {use_icons = false}}
      end
    }
  }
}
```

config file:
```lua
return function()
  require "neogit".setup {
    integrations = {
      diffview = true
    }
  }
end
```

When I press `d` on any file in `:Neogit` diffview tab opens up but no file is listed and there is no diff in neither of the windows - it just looks empty. Everything is up to date including neovim (`v0.5.0-dev+3fe7a0470`).

**Comment by sindrets** [comment] 2021-06-03 21:20
I recently updated diffview, and made some breaking changes in the API. But Neogit has been updated to accommodate those changes. Please make sure you have updated both diffview and neogit.

**Comment by cloggier** [comment] 2021-06-03 21:27
@sindrets Yes, I have updated them both. Behaviour described above is what I experienced since setting up integration (very shortly after it was introduced).

Thanks for all your work on diffview though!

**Comment by sindrets** [comment] 2021-06-03 22:48
Hm, strange. I just tried your config, and it worked fine on my end. This happens in any git repo? And there are no error messages?

Could you please try applying this patch and showing the output after trying to open a diffview from neogit:

```diff
diff --git a/lua/neogit/integrations/diffview.lua b/lua/neogit/integrations/diffview.lua
index 03468e2..3fd3de6 100644
--- a/lua/neogit/integrations/diffview.lua
+++ b/lua/neogit/integrations/diffview.lua
@@ -108,6 +108,7 @@ function M.open(selected_file_name)
 
   view:open()
 
+  print(vim.inspect(view, {depth=1}), vim.inspect(view.files), vim.inspect(view.fetch_files()))
   return view
 end

```

This would help us figure out whether the problem lies in neogit, diffview or something else.

**Comment by cloggier** [comment] 2021-06-05 07:55
Hei, thanks for coming back to me.

It is the same for couple of repositories I checked. Might be something to do with one of my git or nvim setting perhaps? Did not investigate it deeply, just thought will ask here just in case you know about it.

Above statement prints:

```lua
{
  emitter = {...},
  fetch_files = <function 1>,
  file_idx = 1,
  file_panel = {...},
  files = {...},
  get_file_data = <function 2>,
  git_root = "/path/to/repo",
  layout_mode = 1,
  left = {...},
  left_winid = 1006,
  nulled = true,
  ready = true,
  right = {...},
  right_winid = 1007,
  tabpage = 3,
  <metatable> = {...}
} {
  staged = {},
  working = {},
  <metatable> = {
    __index = <function 1>,
    class = <function 2>,
    instanceof = <function 3>,
    ipairs = <function 4>,
    iter = <function 5>,
    new = <function 6>,
    size = <function 7>,
    super = <function 8>,
    <metatable> = <1>{
      __index = <table 1>,
      class = <function 9>,
      instanceof = <function 10>,
      new = <function 11>,
      super = <function 12>
    }
  }
} {
  staged = {},
  working = {}
}
```

**Comment by sindrets** [comment] 2021-06-06 11:20
Okay this tells me that diffview never receives any file data from neogit. Unfortunately I'm not familiar enough with neogit's code base to be able to tell why that might be.

**Comment by TimUntersberger** [comment] 2021-06-07 09:34
This seems very weird. I can reproduce this, but the fix is to set all packages to nil? 😕 

@cloggier can you try to run the following code after confirming the the diffview is empty and then reopening neogit/diffview.

```lua
function invalidate(path, recursive)
    if recursive then
        for key, value in pairs(package.loaded) do
            if key ~= "_G" and value and vim.fn.match(key, path) ~= -1 then
                package.loaded[key] = nil
            end
        end
    else
        package.loaded[path] = nil
    end
end

invalidate("*", true)
```

When this happens for me I press `F3` which is bound to the lua code above and afterwards it works fine. I have no idea why this might happen though. I will have to play with this some more.

**Comment by cloggier** [comment] 2021-06-08 12:19
Not sure what happened but I saw it work once, and tat's it, never worked again. Integration worked after adding your function to my configuration, but didn't even all it. Then tried to run steps you described but it did not make integration to work, still shows empty diffview. Is there anything else I can try to help debugging this?

**Comment by jc00ke** [comment] 2021-06-11 23:26
I'm seeing this too with an updated `neogit` on aca0e8f and `diffview.nvim` on 93c3aba. I tried `invalidate/2` but to no avail. Anything else I can run to help debug?

**Comment by TimUntersberger** [comment] 2021-06-12 12:47
Should be fixed in the latest version. At least I can't reproduce it anymore

**Closed** 2021-06-12 12:47 UTC
Labels: bug

**Comment by cloggier** [comment] 2021-06-12 17:03
Can confirm, working now, huge thanks! Amazing plugins.

**Comment by jc00ke** [comment] 2021-06-12 18:20
Same, works for me, thanks for the quick turnaround! :pray:
