### ISSUE TITLE
Path to gitmessages is not expanded before reading the file

### ISSUE THREAD

**Issue by akinsho** [TimUntersberger/neogit#163] opened 2021-07-11 22:20 UTC
@TimUntersberger thanks for adding in functionality for reading a user's `.gitmessages` 👍🏾. I just tried committing since this change and hit an error

```
...acker/start/plenary.nvim/lua/plenary/async_lib/async.lua:14: The coroutine failed with this message: ...e/nvim/site/pack/packer/opt/neog
it/lua/neogit/lib/uv.lua:25: bad argument #1 to 'lines' (~/.gitmessage: No such file or directory)
```
I found that I'm able to fix this error by changing the path inside my gitconfig to specify the path to the gitmessages as `<full-path>/.gitmessages`, so I think the issue is that before trying to read the gitmessages file the path needs to be expanded.

**Comment by TimUntersberger** [comment] 2021-07-12 08:23
Should be fixed. Thank you!

**Comment by akinsho** [comment] 2021-07-12 08:39
Just tested it out and seems to have fixed the issue 👍🏾. Thanks 💯 

PS: this is definitely an optimisation for the future but it seems to be kind of slow to open the commit buffer now, it takes about 2-3 seconds before it appears on my end 🤷🏾

**Comment by TimUntersberger** [comment] 2021-07-12 14:14
> PS: this is definitely an optimisation for the future but it seems to be kind of slow to open the commit buffer now, it takes about 2-3 seconds before it appears on my end 🤷🏾

This only happens when you have a commit message template.

**Comment by akinsho** [comment] 2021-07-12 14:19
@TimUntersberger I figured as much but I'm still surprised that the whole process takes that long, especially with `libuv` especially versus using Fugitive which is viml and completely synchronous. I was wondering if there is something particularly slow happening. I know where are some gotchas with reading files in lua and some mechanisms being surprisingly slow, not that I know a great deal about it specifically.

**Comment by TimUntersberger** [comment] 2021-07-12 14:28
```lua
    local msg_template_path = cli.config.get("commit.template").call_sync()[1]
    if msg_template_path then
      local msg_template = uv_utils.read_file_sync(vim.fn.glob(msg_template_path))
      for _, line in pairs(msg_template) do
        table.insert(output, line)
      end
      table.insert(output, "")
    end
```
That is the code that is reponsible for the slowness. I don't really know what could be the reason.

**Comment by akinsho** [comment] 2021-07-12 14:47
@TimUntersberger I haven't tried this but did a bit of looking around re. lua and reading files and found a lot of references to using `file:read("*all")` i.e. reading out the whole file and then iterating it with something like `contents:gmatch("\n")`

[This link](https://www.lua.org/pil/21.2.1.html) from the lua book seems to indicate that the performance of reading a file all at once is better than doing it line by line.

> Usually, in Lua, it is much faster to read a file as a whole than to read it line by line. 

Haven't tried this, but tbh looking at [a few other examples](https://www.lua.org/pil/21.1.html) mentioned in the lua book testing (on pentiums 🤣) the speed of `io.lines` seems to be slower but should still be way faster on the hardware I'm, *assuming it is the bottle neck* could just as easily be the git call to get the template dir or something else.

**Comment by TimUntersberger** [comment] 2021-07-12 19:32
@akinsho can you paste your custom git message? I'll try to profile this to see what causes the slowness.

**Comment by akinsho** [comment] 2021-07-12 19:37
@TimUntersberger I'm using this on my personal machine atm, and it's much faster, my work machine runs macOS whereas my personal machine runs Linux 🤷🏾‍♂️. My `gitmessage` file is [here on github](https://github.com/akinsho/dotfiles/blob/0731786f0753043b30f56829aaf9e66fc6afe0b1/git/.gitmessage)

**Comment by TimUntersberger** [comment] 2021-07-12 19:41
> and it's much faster

how much faster are we talking?

**Comment by akinsho** [comment] 2021-07-12 19:50
I was going to try and post a GIF, but that's not working. It takes less than a second on my Linux machine. I will try again tomorrow on my mac with nothing else running in the background and see how it behaves then. It was significantly slower all day, but I run a lot more process simultaneously at work, but have never seen this kind of slowdown before the changes.

**Comment by akinsho** [comment] 2021-07-13 09:00
Wow very strange I thought I replied to this last night but can't see my response 🤕 . Anyway on my Linux machine it takes less than a second whereas on the mac it's closer to 2 seconds. The pause is the wait after the commit popup disappears.

![neogit-slow-commit](https://user-images.githubusercontent.com/22454918/125423330-6b12001c-9499-43b1-a287-4dbd638c751a.gif)

I've got nothing big running at the moment on the mac, really not sure why the large difference in performance

**Comment by TimUntersberger** [comment] 2021-07-14 16:36
I tried to reproduce this locally, but my commit buffer takes maybe 300-400ms to open.

**Comment by TimUntersberger** [comment] 2021-07-14 16:37
I'll close this issue for now.

**Closed by TimUntersberger** 2021-07-14 16:37 UTC

**Comment by akinsho** [comment] 2021-07-14 16:45
Fair enough. It might be an issue local to that system 🤷🏿
