### ISSUE TITLE
"no such file or directory" when committing changes on Windows 10

### ISSUE THREAD

**Issue by RMichelsen** [TimUntersberger/neogit#109] opened 2021-04-13 23:38 UTC
Hi, when I write a commit message and press yes in the commit prompt, I get the following error:
![image](https://user-images.githubusercontent.com/42123601/114634018-f2bc9b00-9cc1-11eb-8819-e06381c4e3c6.png)

`require('neogit').setup {}` is all I have in my `init.lua`

I'm on Windows 10, `NVIM v0.5.0-dev+1233-g82ac44d01`

**Comment by RianFuro** [comment] 2021-04-14 06:57
I noticed this seem to be your dotfiles, so do you perchance have some kind of *bare*-checkout, where the worktree is disconnected from the repository? We currently have some problems with commits on setups like that.

**Comment by RMichelsen** [comment] 2021-04-14 07:14
I dont believe so, the repo has simply been cloned without anything fancy

**Comment by RMichelsen** [comment] 2021-04-14 19:38
Upon further investigation I believe that maybe `cwd` isn't being set properly. This is what is being given as the parameters
```
  args = { "commit", "--file=.git/NEOGIT_COMMIT_EDITMSG" },
  cwd = "",
  stdio = { <userdata 1>, <userdata 2>, <userdata 3> }
```
most other places have cwd set to the right path.

**Comment by RMichelsen** [comment] 2021-04-14 22:04
I have temporarily fixed the issue by using `vim-rooter`, so I am pretty confident that the issue is the wrong `cwd` is being passed.

**Comment by RianFuro** [comment] 2021-04-15 19:10
Yeah I can reproduce the problem when the cwd is not the repository root. We currently have some problems there and are tracking the issue in #91. Thus, closing as duplicate :)

**Comment by RianFuro** [comment] 2021-04-15 19:20
Actually, one thing doesn't sit right with me: Can you do me a favor and track the call to `git rev-parse` that's made for the call to `commit`? It's supposed to give you the root directory of the repository you're in, but apparently it doesn't for you. Cannot reproduce that specific part of the problem either

The relevant call is made in the function `git_root` in `lib/git/cli.lua`. Would also be interesting where your cwd is in that moment relative to your repository root.

**Comment by RMichelsen** [comment] 2021-04-15 19:28
I believe its because the call is made when editing the file inside the `.git` folder, when I run `git rev-parse --show-toplevel` inside the `.git` folder I get `fatal: this operation must be run in a work tree`, inside the actual folder containing my `init.lua` it works fine and gives me `C:/Users/Rasmus/AppData/Local/nvim`

**Comment by RianFuro** [comment] 2021-04-15 19:39
Ah, that's interesting. Does your neovim change working directory when opening a file to the directory containing the file? (without `vim-rooter`) Afaik the cwd should just be copied from the last window that had focus before the new buffer was opened. (excluding autocommands of course)

**Comment by RMichelsen** [comment] 2021-04-15 19:44
It depends whether or not you have the `autochdir` set I think. I believe without `autochdir` I wasn't getting any output from the `:Neogit` status pane either because my current directory wasn't even inside the git repository.

**Comment by RianFuro** [comment] 2021-04-15 19:47
`	Note: When this option is on some plugins may not work.` Haha, it even gives a general warning in the manual :sweat_smile: 

Good, I learned a thing today, thanks :) I'll see what I can do about that

**Comment by RMichelsen** [comment] 2021-04-15 19:53
Hahah I had no idea that was the case either, I suppose it makes sense. Many of the project-root-finding plugins disable the setting.

**Comment by TimUntersberger** [comment] 2021-05-17 16:50
So should we close this as `wontfix` or modify `autochdir` ?

**Comment by RianFuro** [comment] 2021-05-17 17:01
I think setting noautochdir on our own buffers is perfectly fine. Beyond that I thought maybe we should associate neogit buffers with a repository object when they are opened and then just reference back to that when doing stuff opening new windows. Would be a lot easier to reason about compared to currently and also allow us to open neogit buffers regardless of the current working directory, by just prompting the user to input a path manually (like magit does aswell). Didn't find the time recently to continue down that path though..

Definitely wouldn't close it as wontfix though

**Comment by TimUntersberger** [comment] 2021-05-17 17:27
So I guess as a quick fix we should set `noautochdir` and later on refactor the code a bit.

**Comment by TimUntersberger** [comment] 2021-05-17 17:34
Should be fixed in the latest version.

**Comment by TimUntersberger** [comment] 2021-05-17 17:34
@RianFuro I also think we should slowly start to refactor the `status.lua` file, because honestly this is has become quite the disgusting beast haha.

**Closed** 2021-07-11 14:31 UTC
Labels: bug
