### ISSUE TITLE
Close function doesn't close the buffer

### ISSUE THREAD

**Issue by caenrique** [TimUntersberger/neogit#176] opened 2021-07-27 16:20 UTC
The reason is to integrate this with auto-session plugins hooks, so the neogit tab doesn't get saved into a session and breaks when reloaded. 
I currently have a simple workaround implementing this a as function with lua, but it would be nice if this is included here I think

Edit:

I saw that there is one function exposed as `close` that points to [this function](https://github.com/TimUntersberger/neogit/blob/ee83d4fa8ac946e5e0064e65a5276e1ea030ae28/lua/neogit/status.lua#L407) but I don't understand why instead of closing the buffer like [here](https://github.com/TimUntersberger/neogit/blob/ee83d4fa8ac946e5e0064e65a5276e1ea030ae28/lua/neogit/status.lua#L670) (which is only possible if the current buffer is the neogit status buffer) it just de-references the status_buffer

This means I cannot use this function to close NeogitStatus from another tab

**Comment by TimUntersberger** [comment] 2021-07-29 20:06
> I saw that there is one function exposed as close that points to this function but I don't understand why instead of closing the buffer like here (which is only possible if the current buffer is the neogit status buffer) it just de-references the status_buffer

Well that is a bug 😆

**Comment by Shatur** [comment] 2021-08-02 19:25
After this change `:bdelete` breaks neogit.

**Comment by TimUntersberger** [comment] 2021-08-02 19:53
@Shatur what do you mean exactly?

**Comment by Shatur** [comment] 2021-08-02 20:00
@TimUntersberger sorry, I definitely should be more specific 😄 
If i open `:Neogit kind=vsplit` and use `:bd` - I will have the following error after a delay:

```
|| Error executing vim.schedule lua callback: ...ugins\start\plenary.nvim\lua\plenary\async_lib\async.lua:14: The coroutine failed with this message: ...l\nvim\pack\plugins\opt\neogit\lua\neogit\lib\buffer.lua:109: Invalid buffer id: 8
```

After it `:Neogit` will do nothing.
Can you reproduce this error?

**Comment by TimUntersberger** [comment] 2021-08-02 21:43
I can't reproduce this.

**Comment by TimUntersberger** [comment] 2021-08-02 21:48
Should be fixed now.

**Comment by Shatur** [comment] 2021-08-02 21:49
Thanks, works as expected now!

**Closed** 2021-08-02 22:01 UTC
Labels: bug
