### ISSUE TITLE
Neogit Issue with 0.8 stable

### ISSUE THREAD

**Issue by milkias17** [TimUntersberger/neogit#368] opened 2022-10-03 20:46 UTC
### Description

If I'm in a non-git repository directory, neogit throws a bunch of errors on 0.8. The errors:
```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesytem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

### Neovim version

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by linuxbrew@04d933e5bf3e

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/linuxbrew/.linuxbrew/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info

### Operating system and version

Linux 5.14

### Steps to reproduce

1. Go to a directory that isn't a git repo.
2. Open neovim and then run :messages, or just quit neovim
3. You should see the errors previously shown.

### Actual behavior

![image](https://user-images.githubusercontent.com/66522725/193678942-4735363e-ee95-4204-850d-23d184fa7ee9.png)

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by tastytea** [comment] 2022-10-05 18:06
seems to be a duplicate of #349

**Comment by anachronic** [comment] 2022-10-27 03:45
@milkias17 since https://github.com/TimUntersberger/neogit/issues/349 was closed, might we close this?

**Closed** 2022-10-27 20:53 UTC
Labels: bug
