### ISSUE TITLE
Diffview integration fails with an error

### ISSUE THREAD

**Issue by Utkarsh-khambra** [TimUntersberger/neogit#387] opened 2022-10-30 07:47 UTC
### Description

I recently updated Neogit from commit 3fab92b376655277eec15d36b75f850176b6f4d4 to 1acb13c07b34622fe1054695afcecff537d9a00a and I noticed that whenever I press `d` to see the diffs I either get an error like this 
![Screenshot from 2022-10-30 12-48-06](https://user-images.githubusercontent.com/29328319/198867036-3d1716fd-99de-497c-9d65-a35897fcae27.png)

error
```
fatal: path 'src/terminal/Line.h' is in the index, but not 'terminal/Line.h'
hint: Did you mean ':0:src/terminal/Line.h' aka ':0:./terminal/Line.h'?

```
when my cwd is not the root of git directory.
or a wrong diff as shown.
![Screenshot from 2022-10-30 12-46-59](https://user-images.githubusercontent.com/29328319/198867043-aa429a2f-9dac-48da-b942-f0726d0dc483.png)
(The actual change here is an addition of line `#include <regex>` but it shows that more lines have been added here)

Invoking Diffview manually with command `DiffviewOpen master` shows the correct diffs. Commit 3fab92b376655277eec15d36b75f850176b6f4d4 is working fine for me. 

### Neovim version

NVIM v0.9.0-dev-135-g96cf385a7
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

Fedora 36

### Steps to reproduce

1. Update to latest commit
2.  Open neovim from directory that is not a root of your git directory.
3.  Run neogit and press d to see diffs, this should show the error
4.  Or run neovim from root of git directory to see the wrong diffs.

### Actual behavior

I get errors when I try to see diffs for files when neovim is not started in root of git directory or wrong diffs when neovim is started in root of git directory.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			{
				"TimUntersberger/neogit",
				requires = {
					{ "nvim-lua/plenary.nvim" },
					{
						"sindrets/diffview.nvim",
						config = function()
							require("diffview").setup({ use_icons = false, diff_binaries = true })
						end,
					},
				},
				config = function()
					print("loaded neogit")
					require("neogit").setup({ integrations = {
						diffview = true,
					} })
				end,
			},
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
			display = { non_interactive = true },
		},
	})
end
if vim.fn.isdirectory(install_path) == 0 then
	print("Installing neogit and dependencies.")
	vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()

```

**Comment by ten3roberts** [comment] 2022-10-30 18:41
Do the incorrect diffs only occur when diffing against the HEAD, as in unstaged changes, or when diffing against a certain commit in the recent section?

**Comment by Utkarsh-khambra** [comment] 2022-10-30 19:00
Yes incorrect diffs only occur when diffing against the unstaged changes. Diff from the recent section are correct.

**Comment by ten3roberts** [comment] 2022-10-30 19:01
As for the first one, is that when opening neovim inside the repo, but the cwd a level lower, so that the `.git` is `../`

**Comment by Utkarsh-khambra** [comment] 2022-10-30 19:37
I see wrong diffs no matter what my cwd is.
But when my cwd is not the root of the git repo then I get error for files that are one level lower
But for files in cwd I  either see error or files being diffed is wrong file entirely. 
If go down one level from the root of the repo then file in cwd is diffed like this
![Screenshot from 2022-10-31 00-55-10](https://user-images.githubusercontent.com/29328319/198897768-b3d8103b-3b80-44df-85f4-00742e794ad9.png)
But actually it is the wrong file, correct file looks like this
![Screenshot from 2022-10-31 00-58-16](https://user-images.githubusercontent.com/29328319/198897812-4747723d-1b17-4fa9-9c4a-8b4e6f0d9d23.png)

But if files have paths like `../<something>` I see diffs like everything has been added in this change
![Screenshot from 2022-10-31 01-00-19](https://user-images.githubusercontent.com/29328319/198898135-1afd80d1-fc86-4a6f-a2b1-d0139504d0e4.png)

**Comment by ten3roberts** [comment] 2022-10-30 22:10
Hopefully most of the issues should be fixed.

There is still an issue where an extra blankline is included at the end of the files, I will be looking into it as soon as I can

**Comment by Utkarsh-khambra** [comment] 2022-10-31 04:44
Thanks. Yes all of the issues I had, have been fixed, the only remaining one is a newline at the end of file.

**Comment by ten3roberts** [comment] 2022-11-05 17:24
The blanklines are now fixed. It was caused by git, like cat, adding an extra blankline to the output

#396

**Comment by Utkarsh-khambra** [comment] 2022-11-05 19:34
Thanks for working on it.

**Closed** 2022-11-07 09:21 UTC
Labels: bug
