### ISSUE TITLE
Diffview doesn't respect cwd change

### ISSUE THREAD

**Issue by Shatur** [TimUntersberger/neogit#130] opened 2021-05-19 19:28 UTC
If I change the current folder and start working on a different repository, then diffview still keeps opening for the old repository (Neogit itself works correctly).

**Steps to reproduce**

1. Open any repository with changes.
2. Open diffview, you should see your changes.
3. Switch to another folder.
4. Open Neogit, you will see changes for the new opened repo.
5. Navigate to any hunk and press `d`.

You will see changes from the previous repo.

**Comment by TimUntersberger** [comment] 2021-06-12 12:55
This should be fixed in the latest version. I can't reproduce this anymore.

**Closed by TimUntersberger** 2021-06-12 12:55 UTC
Labels: bug
