### ISSUE TITLE
Failed press `d` on commit or stash

### ISSUE THREAD

**Issue by timsofteng** [TimUntersberger/neogit#286] opened 2022-05-03 12:38 UTC
### Description

It would be nice to have diff for commits to head or master to toggle `d` on commit.
Or maybe compare commits between each other.
Like press `d` on by one.

Now if you press `d` on commit you get error

### Neovim version

nvim 0.7

### Operating system and version

Alpine edge

### Steps to reproduce

1. Press `d` on any commit.

### Expected behavior

should work...

### Actual behavior

```
Error executing vim.schedule lua callback: ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...tart/diffview.nvim/lua/diffview/views/diff/diff_view.lua:274: attempt to index field 'options' (a nil value)
stack traceback:
        [C]: in function 'error'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:40: in function <...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:39>
```

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by EpiCanard** [comment] 2022-05-06 21:30
@timsofteng The fix is merged, you can close this issue if you are satisfied with the fix.

**Comment by timsofteng** [comment] 2022-05-06 23:00
@EpiCanard cool thanks. Now it works.
But now it's error on pressing enter on commit. Is it shared issue or should I open new one?

**Comment by EpiCanard** [comment] 2022-05-07 14:59
@timsofteng I can't reproduce your bug. When I press enter on commit it display normal diff view on the side.
So I guess you can open a new issue.

**Comment by timsofteng** [comment] 2022-05-08 13:10
@EpiCanard can't reproduce it second time.
So I close the issue.
Thanks.

**Closed** 2022-05-08 17:04 UTC
Labels: bug
